### ISSUE TITLE
Duda con threads y servidor

### ISSUE THREAD

**Issue by taprile314** [neubatengog/FlaskMqtt#1]
Hola, estoy escribiendo un servidor muy parecido, estoy usando socketio para hablar con el navegador y mqtt para comunicarme entre un arduino y el server. En tu código ví que armaste un thread para el sub de mqtt, esto es para que no interrumpa lo que pasa en el otro hilo?

También te quería preguntar si todo esto lo pusiste en producción usando ngnix+gunicorn o algún wsgi ya que como se está usando eventlet es todo medio raro y estoy medio perdido. Mil gracias por compartir tu código!

**Comment by neubatengog** [comment]
Hola,
Realmente ese código hace bastante tiempo, lo que realice fue bastante
rapido y si lo recuerdo fue justamente como tu mencionas para levantar otro
proceso para no interrumpir ese hilo.  Funciono en producción justamente
con gunicorn y nginx.
Voy a revizar el codigo para ver si tengo cambios que se hayan realizados

**Comment by taprile314** [comment]
Gracias por responder! Entonces veo que no estaba tan equivocado.
Estoy usando esta librería para mqtt : https://github.com/stlehmann/Flask-MQTT
y tienen problemas usando más de 1 worker a la vez. Tuviste que limitar a 1 worker en gunircorn o pudiste utilizar más de uno?
Ví que estás usando la librería de paho directamente, si funcionaba bien así entonces creo que lo voy a implementar como hiciste vos

**Comment by neubatengog** [comment]
Si por limitante solo se puede un solo worker

**Comment by taprile314** [comment]
Ok, te cierro el issue entonces
Mil gracias por tu ayuda!
